// KØS SEJL — service worker: precache every game file, then serve cache-first (fully offline after first visit).
// The block between the precache markers is generated by `node tools/gen-precache.js` — do not edit by hand.
// A new VERSION (hash of all files) installs a new cache; the page shows a "new version" toast and posts
// {type: 'skipWaiting'} when the player taps "Opdater".
// <precache> generated by tools/gen-precache.js - do not edit by hand
const VERSION = '60953acd756e';
const PRECACHE = [
  'index.html',
  'manifest.webmanifest',
  'css/controls.css',
  'css/game.css',
  'css/hub.css',
  'css/modes/capsize.css',
  'css/modes/dock.css',
  'css/modes/knots.css',
  'css/modes/nav.css',
  'css/modes/quiz.css',
  'css/modes/race.css',
  'css/modes/rib.css',
  'css/modes/rigging.css',
  'css/modes/rowschool.css',
  'css/modes/sail.css',
  'css/modes/school.css',
  'css/modes/shed.css',
  'css/style.css',
  'js/core/activities.js',
  'js/core/ai.js',
  'js/core/boats.js',
  'js/core/i18n.js',
  'js/core/kos.js',
  'js/core/physics.js',
  'js/core/rules.js',
  'js/core/wind.js',
  'js/core/world.js',
  'js/main.js',
  'js/modes/capsize.js',
  'js/modes/dock.js',
  'js/modes/knots.js',
  'js/modes/nav.js',
  'js/modes/quiz.js',
  'js/modes/race.js',
  'js/modes/rib.js',
  'js/modes/rigging.js',
  'js/modes/rowschool.js',
  'js/modes/sail.js',
  'js/modes/school.js',
  'js/modes/shed.js',
  'js/render/effects.js',
  'js/render/scene.js',
  'js/render/sprites.js',
  'js/render/water.js',
  'js/ui/app.js',
  'js/ui/audio.js',
  'js/ui/hub.js',
  'js/ui/input.js',
  'js/ui/sailaids.js',
  'js/ui/storage.js',
  'js/ui/track.js',
  'js/ui/ui.js',
  'assets/bg/club.jpg',
  'assets/bg/hub-land.jpg',
  'assets/bg/hub-port.jpg',
  'assets/bg/race.jpg',
  'assets/bg/results.jpg',
  'assets/bg/title-land.jpg',
  'assets/bg/title-port.jpg',
  'assets/bg/winter.jpg',
  'assets/icons/app/icon-192.png',
  'assets/icons/app/icon-512.png',
  'assets/icons/app/icon-maskable-512.png',
  'assets/icons/app/icon.svg',
];
// </precache>

const CACHE = 'kos-sejl-' + VERSION;

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE).then(cache =>
      // './' and index.html are both entry points (start_url is './')
      cache.addAll(['./'].concat(PRECACHE).map(u => new Request(u, { cache: 'reload' })))
    )
  );
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k.startsWith('kos-sejl-') && k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('message', event => {
  const d = event.data || {};
  if (d.type === 'skipWaiting') self.skipWaiting();
  else if (d.type === 'version' && event.source) event.source.postMessage({ type: 'version', version: VERSION });
});

self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  // navigations: serve the cached shell (ignoring ?query and #hash), fall back to network
  if (req.mode === 'navigate') {
    event.respondWith(
      caches.match('index.html', { cacheName: CACHE })
        .then(hit => hit || fetch(req))
        .catch(() => caches.match('./'))
    );
    return;
  }
  event.respondWith(
    caches.match(req, { cacheName: CACHE, ignoreSearch: true }).then(hit => {
      if (hit) return hit;
      return fetch(req).then(res => {
        // runtime-cache anything same-origin that was missed by the precache list
        if (res && res.ok && res.type === 'basic') {
          const copy = res.clone();
          caches.open(CACHE).then(c => c.put(req, copy)).catch(() => {});
        }
        return res;
      });
    })
  );
});
