// Renders the static layer of the hub map (sea, depth, land, city blocks, coast, piers, moored boats, buoys, ...) into
// the base images the hub shows instead of a 480 KB / 3,500-node SVG (old iPhones took 15-20 s to paint that one).
//
//   node tools/render-hub.js            regenerate assets/hub/hub-map-1x.webp, -2x.webp, -1x.jpg and hub-map.json
//   node tools/render-hub.js --check    exit 1 if the images are stale (hash of the static art != hub-map.json)
//   options: --q=0.80 (webp quality 0-1)  --jq=0.82 (jpg quality)
//
// The art is hub.js buildMap('static') (map data from js/world*.js + STATIC_CSS in hub.js). hub-map.json stores a hash of
// that markup, so `--check` (also the `hubimg` suite of tools/run-tests.js) fails when the art changed but the images
// were not regenerated. Use the full vector map while editing the art: open the game with #hubsvg=1.
// Headless Chrome only; never opens a window.
const { chromium } = require('playwright');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const url = require('url');

const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'assets', 'hub');
const opt = (n, d) => { const a = process.argv.find(x => x.startsWith('--' + n + '=')); return a ? +a.split('=')[1] : d; };
const CHECK = process.argv.includes('--check');

(async () => {
  const browser = await chromium.launch({ headless: true, channel: 'chrome' });
  const page = await browser.newPage({ viewport: { width: 800, height: 600 } });
  await page.goto(url.pathToFileURL(path.join(ROOT, 'index.html')).href);
  await page.waitForFunction(() => window.KOS && KOS.Hub && KOS.World && KOS.Hub.staticSvg, null, { timeout: 20000 });
  const svg = await page.evaluate(() => KOS.Hub.staticSvg());
  const W = +/ width="(\d+)"/.exec(svg)[1], H = +/ height="(\d+)"/.exec(svg)[1];
  const hash = crypto.createHash('sha256').update(svg).digest('hex').slice(0, 16);
  let meta = null;
  try { meta = JSON.parse(fs.readFileSync(path.join(OUT, 'hub-map.json'), 'utf8')); } catch (e) { /* none yet */ }
  if (CHECK) {
    await browser.close();
    const files = ['hub-map-1x.webp', 'hub-map-2x.webp', 'hub-map-1x.jpg'];
    const missing = files.filter(f => !fs.existsSync(path.join(OUT, f)));
    if (missing.length || !meta || meta.hash !== hash) {
      console.error('hub map images are STALE (art hash ' + hash + ', images ' + (meta ? meta.hash : 'missing') + (missing.length ? ', missing ' + missing.join(' ') : '') + ').');
      console.error('Run: node tools/render-hub.js   (then node tools/gen-precache.js)');
      process.exit(1);
    }
    console.log('hub map images up to date (' + hash + ')');
    return;
  }

  fs.mkdirSync(OUT, { recursive: true });
  const q = opt('q', 0.8), jq = opt('jq', 0.82);
  const sizes = {};
  for (const [scale, kinds] of [[1, ['webp', 'jpg']], [2, ['webp']]]) {
    const ctx = await browser.newContext({ viewport: { width: W, height: H }, deviceScaleFactor: scale });
    const p = await ctx.newPage();
    await p.setContent('<!doctype html><html><body style="margin:0;background:#1b3f80">' + svg + '</body></html>');
    await p.waitForTimeout(300);
    const png = (await p.screenshot({ type: 'png', clip: { x: 0, y: 0, width: W, height: H } })).toString('base64');
    await ctx.close();
    for (const kind of kinds) {
      const b64 = await page.evaluate(async ({ png, kind, q }) => {
        const img = new Image(); img.src = 'data:image/png;base64,' + png; await img.decode();
        const c = document.createElement('canvas'); c.width = img.naturalWidth; c.height = img.naturalHeight;
        c.getContext('2d').drawImage(img, 0, 0);
        return c.toDataURL(kind === 'webp' ? 'image/webp' : 'image/jpeg', q).split(',')[1];
      }, { png, kind, q: kind === 'webp' ? q : jq });
      const name = 'hub-map-' + scale + 'x.' + kind;
      const buf = Buffer.from(b64, 'base64');
      fs.writeFileSync(path.join(OUT, name), buf);
      sizes[name] = buf.length;
      console.log(name, (buf.length / 1024).toFixed(0) + ' KB');
    }
  }
  fs.writeFileSync(path.join(OUT, 'hub-map.json'), JSON.stringify({ hash, width: W, height: H, files: sizes, note: 'generated by tools/render-hub.js - do not edit' }, null, 2) + '\n');
  await browser.close();
  console.log('hash', hash, '- now run: node tools/gen-precache.js');
})().catch(e => { console.error(e); process.exit(1); });
